## =============================================================================
## ZedBoard (Avnet) - Zynq-7000 SoC (xc7z020clg484-1)
## Pin Constraints File for Video Accelerator Project
## Student: G. Sai Ram (1602-24-735-163)
## =============================================================================

## ============================================================
## System Clock - 100 MHz (from FCLK_CLK0 generated by PS)
## ============================================================
# PL fabric clock generated from PS - no physical pin needed
# The FCLK_CLK0 is internal to the Zynq PS block and connected
# via the block design. No external clock pin constraint required.

## ============================================================
## User Push Buttons (active high)
## ============================================================
set_property PACKAGE_PIN P16 [get_ports {btnc}]
set_property IOSTANDARD LVCMOS25 [get_ports {btnc}]

set_property PACKAGE_PIN R16 [get_ports {btnd}]
set_property IOSTANDARD LVCMOS25 [get_ports {btnd}]

set_property PACKAGE_PIN N15 [get_ports {btnl}]
set_property IOSTANDARD LVCMOS25 [get_ports {btnl}]

set_property PACKAGE_PIN R18 [get_ports {btnr}]
set_property IOSTANDARD LVCMOS25 [get_ports {btnr}]

set_property PACKAGE_PIN T18 [get_ports {btnu}]
set_property IOSTANDARD LVCMOS25 [get_ports {btnu}]

## ============================================================
## User Slide Switches (8 switches)
## ============================================================
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[0]}]

set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[1]}]

set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[2]}]

set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[3]}]

set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[4]}]

set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[5]}]

set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[6]}]

set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[7]}]

## ============================================================
## User LEDs (8 LEDs, active high)
## ============================================================
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]

set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]

set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]

set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]

set_property PACKAGE_PIN U14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

## ============================================================
## UART - USB-to-UART Bridge (for debug / PuTTY @ 115200 baud)
## ============================================================
# Note: UART is routed through the PS in Zynq block design.
# No explicit PL pin constraint is needed if using PS UART0/UART1.
# The physical pins are:
#   TX: MIO 48 -> USB UART Bridge on ZedBoard
#   RX: MIO 49 -> USB UART Bridge on ZedBoard
# These are configured in the Zynq PS block design, not here.

## ============================================================
## Video Accelerator Interrupt Line (to Zynq PS PL-to-PS IRQ)
## ============================================================
# The IRQ signal is connected internally in the Block Design
# from the PL accelerator to the Zynq PS IRQ_F2P[0:0].
# No external pin constraint needed.

## ============================================================
## OLED Display (SSD1306 via SPI)
## ============================================================
set_property PACKAGE_PIN U10 [get_ports {oled_dc}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_dc}]

set_property PACKAGE_PIN U9 [get_ports {oled_res}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_res}]

set_property PACKAGE_PIN AB12 [get_ports {oled_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_sclk}]

set_property PACKAGE_PIN AA12 [get_ports {oled_sdin}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_sdin}]

set_property PACKAGE_PIN U11 [get_ports {oled_vbat}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_vbat}]

set_property PACKAGE_PIN U12 [get_ports {oled_vdd}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_vdd}]

## ============================================================
## HDMI Output (ADV7511 - via I2C + TMDS)
## ============================================================
# NOTE: HDMI output requires ADV7511 I2C configuration via PS I2C0
# and TMDS data lines routed as LVDS pairs. Our design uses AXI DMA
# (not HDMI) for video output. HDMI pins are reserved here for
# future expansion.
set_property PACKAGE_PIN W18 [get_ports {hdmi_clk_n}]
set_property PACKAGE_PIN V18 [get_ports {hdmi_clk_p}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk_n}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk_p}]

## ============================================================
## Timing Constraints
## ============================================================
# Main AXI clock from Zynq PS FCLK_CLK0 @ 100 MHz
# (Defined in Block Design; period = 10.0 ns)
# create_clock -period 10.000 -name clk_100mhz [get_pins zynq_ps/FCLKCLK[0]]

## ============================================================
## Bitstream Configuration Settings
## ============================================================
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLDOWN [current_design]
